# Generated by Django 5.2.6 on 2025-09-25 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Employee',
            new_name='car',
        ),
    ]
